export enum DiceStyle {
  SHARP = "SHARP",
  ROUNDED = "ROUNDED",
  GLASS = "GLASS",
  GALAXY = "GALAXY",
  GEMSTONE = "GEMSTONE",
  IRON = "IRON",
  NEBULA = "NEBULA",
  SUNRISE = "SUNRISE",
  SUNSET = "SUNSET",
  WALNUT = "WALNUT"
}
